USE [master]
GO

/****** Object:  Database [testSTK]    Script Date: 5/26/2019 2:16:28 PM ******/
CREATE DATABASE [testSTK]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'testSTK', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\testSTK.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'testSTK_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\testSTK_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [testSTK].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [testSTK] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [testSTK] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [testSTK] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [testSTK] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [testSTK] SET ARITHABORT OFF 
GO

ALTER DATABASE [testSTK] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [testSTK] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [testSTK] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [testSTK] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [testSTK] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [testSTK] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [testSTK] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [testSTK] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [testSTK] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [testSTK] SET  DISABLE_BROKER 
GO

ALTER DATABASE [testSTK] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [testSTK] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [testSTK] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [testSTK] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [testSTK] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [testSTK] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [testSTK] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [testSTK] SET RECOVERY FULL 
GO

ALTER DATABASE [testSTK] SET  MULTI_USER 
GO

ALTER DATABASE [testSTK] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [testSTK] SET DB_CHAINING OFF 
GO

ALTER DATABASE [testSTK] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [testSTK] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [testSTK] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [testSTK] SET QUERY_STORE = OFF
GO

ALTER DATABASE [testSTK] SET  READ_WRITE 
GO

